Algoritmo "Caso"

Var
X : inteiro
dia : caracter


Inicio

Escreva("Digite um número e e te direi a qual dia da semana ele se refere:")
  Leia(x)

  Escolha x
  caso 1
  dia <- "Domingo"
  caso 2
  dia <- "segunda"
  caso 3
  dia <- "Quarta"
  caso 4
  dia <- "Quinta"
  caso 5
  dia <- "Sexta"
  caso 6
  dia <- "Sabado"
  outrocaso
  dia <- "Valor inválido"
  Fimescolha
  
  Escreval ("Dia da semana: ",dia))

Fimalgoritmo