Algoritmo "semnome"

Var
V1, V2, V3 : real



Inicio

Escreva ("Digite o primeiro valor: ")
Leia (V1)
Escreva ("Digite o segundo valor: ")
Leia (V2)
Escreva ("Digite o terceiro valor: ")
Leia (V3)

   Se V1 < V2 e V3 então
      Escreval ("O menor valor é: ",V1)
   senão
     Se V2 < V1 e V3 então
      Escreval ("O menor valor é: ",V2)
      Senão
      Escreval ("O menor valor é: ",V3)
     Fimse
   Fimse






Fimalgoritmo